---
- name: Check the NTP status.
  shell: "timedatectl status"
  register: output_1

- debug:
   var: output_1.stdout_lines


- name: Add NTP servers.
  become: true
  become_user: root
  shell: 'echo "Servers=0.debian.pool.ntp.org 
  1.debian.pool.ntp.org" >> /etc/systemd/timesyncd.conf'
  register: output_1

- debug:
   var: output_1.stdout_lines


- name: Check the NTP config file.
  shell: "cat /etc/systemd/timesyncd.conf"
  register: output_1

- debug:
   var: output_1.stdout_lines


- name: Turn on NTP.
  become: true
  become_user: root
  shell: "timedatectl set-ntp true"
  register: output_1

- debug:
   var: output_1.stdout_lines
  

- name: Check the NTP status.
  shell: "timedatectl status"
  register: output_1

- debug:
   var: output_1.stdout_lines
  
