#Dockerfile to create a NodeJS app image from a base image.

#Use the official node image.
FROM localhost:5000/base-nodejs:v1

#Set the working directory.
WORKDIR /root/app-1-web

#Copy code repository files
ADD ./source .

#Set the working directory.
WORKDIR /root/app-1-web/source

#Initialize the project.
RUN npm install -y

#Install the express framework.
#RUN npm install express

#Install pm2.
#RUN npm install pm2@latest -g

#Listen to port 3000.
EXPOSE 3000

#Start the nodejs server.
CMD ["npm", "start"]

#CMD tail -f /dev/null
