apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: default
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:

     imagePullSecrets:
     - name: docker-registry
     
     containers:
     - name: nginx
       image: ranuldeepanayake/private:nginx
       ports:
       - containerPort: 80
