#Dockerfile to create a MySQL image from a base image.

#Use the official node image.
FROM 192.168.1.31:5000/base-mysql:v1

#Set the working directory.
WORKDIR /root

#Listen to port 3000.
EXPOSE 3306
