#Dockerfile to create a MySQL image from a base image.

#Use the official node image.
FROM localhost:5000/base-phpmyadmin:v1

#Set the working directory.
WORKDIR /root

#Listen to port 3000.
EXPOSE 80