#Dockerfile to create an nginx based web server.

#Use the official nginx image.
FROM nginx:latest

#Copy the source code.
ADD /home/ranul/workspace/DOCKERFILE_SOURCE_CODE_PATH/nginx/index.html /usr/share/nginx/html

#Set the working directory.
#WORKDIR /root/mysql
