FROM node:latest
WORKDIR /home/node/app
ADD /home/ranul/repos/node-app/nodejs-s3 .
RUN npm install
RUN npm install express multer aws-sdk
EXPOSE 80
CMD [ "node", "server.js" ]
#ENTRYPOINT [ "php", "./index.php" ]
#RUN php ./index.php