#Dockerfile to create an nginx based web server.

#Use the official nginx image.
FROM nginx:latest

#Copy the source code.
ADD /home/ranul/workspace/DOCKERFILE_SOURCE_CODE_PATH/nginx/index.html /usr/share/nginx/html

#Update the repository cache.
#RUN apt update

#Install vim.
#RUN apt install vi -y

#Create a certificate.
RUN openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
    -subj "/C=LK/ST=Western/L=Colombo/O='Hamadaama Server Down'/CN=192.168.56.129" \
    -keyout /home/node-app-dev.key  -out /home/node-app-dev.cert

#Copy the modified nginx configuration file.
ADD /home/ranul/workspace/DOCKERFILE_SOURCE_CODE_PATH/nginx/default.conf /etc/nginx/conf.d

#The entry point will automatically start the nginx service.
#The docker file will automatically enter the entry point. Any 

