FROM node:latest
WORKDIR /home/node/app
ADD DOCKERFILE_SOURCE_CODE_PATH/nodejs-s3 .
RUN npm install
RUN npm install express multer aws-sdk
EXPOSE 80

ENV AWS_AKID='AKIA6ODU27O6DEPBFRQD'
#ENV AWS_SAK='7gbiLuTU56YQtgGjd/54SyKJhRTVr2I92/YPzFi8' #Passed as an env variable from the kubernetes yaml instead.

CMD [ "env" ]
CMD [ "node", "server.js" ]
#ENTRYPOINT [ "php", "./index.php" ]
#RUN php ./index.php