---
  - name: A test playbook.
    hosts: host-1

    vars_files:
     - /home/ranul/ansible/group-vars/primary-vault.yml  
   
    tasks:
     - name: Get the hostname.
       shell: "hostname"
       register: output_1
       no_log: true

     - debug: 
          var: output_1.stdout_lines


     - name: Get IPv4 interfaces.
       shell: "ifconfig | grep inet"
       register: output_1
       no_log: true

     - debug:
          var: output_1.stdout_lines


     - name: Update the package repository.
       become: true
       shell: "apt update"
       register: output_1
       no_log: false

     - debug:
          var: output_1.stdout_lines
