---
  - name: A playbook for NTP operations.
    hosts: ansible-controllers:&host-2
    become: true
    become_user: ranul

    vars_files:
     - /home/ranul/ansible/group-vars/primary-vault.yml  
   
    roles:
     - { role: /home/ranul/ansible/roles/ntp-update }