---
  - name: A playbook to deploy a containerized application.
    hosts: host-1
    become: true
    become_user: ranul

    vars_files:
     - /home/ranul/ansible/group-vars/primary-vault.yml  
   
    roles:
     - { role: /home/ranul/ansible/roles/app-1-deploy }