apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodejs-s3-deployment
  namespace: default
  
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: nodejs-s3

  template:
    metadata:
      labels:
        app: nodejs-s3
    spec:

     imagePullSecrets:
     - name: docker-registry
     
     containers:
     - name: nodejs-server
       image: ranuldeepanayake/private:nodejs-s3
       imagePullPolicy: "Always"
       ports:
       - containerPort: 80
       env:
       #- name: AWS_SAK
       #  value: 7gbiLuTU56YQtgGjd/54SyKJhRTVr2I92/YPzFi8
       #resources:
        #    requests:
         #     cpu: 100m
          #    memory: 128Mi
           # limits:
            #  cpu: 250m
             # memory: 256Mi
