apiVersion: v1
kind: Pod
metadata:
  name: app-1-pod
  namespace: default
spec:
  containers:
  - name: app-1-web
    image: 192.168.1.31:5000/app-1:web
      #imagePullPolicy: Never
    ports: 
    - containerPort: 80
