---
dc:
 children:
  ansible-controllers:
   hosts:
    host-1:
     ansible_host: 192.168.1.30 
     ansible_port: 22 
     ansible_user: ranul
     ansible_ssh_pass: "{{vault_password_1}}" 

    host-2:
     ansible_host: 192.168.1.31 
     ansible_port: 22 
     ansible_user: ranul
     ansible_ssh_pass: "{{vault_password_1}}" 

kubernetes-hosts:
 children:
  kubernetes-masters:
   hosts:
    kubernetes-master-1:
     ansible_host: 192.168.1.35 
     ansible_port: 22 
     ansible_user: ranul
     ansible_ssh_pass: "{{vault_password_1}}" 

docker-hosts:
linux:
windows:

all:
 children:
  dc: